image: java:8-jdk

services:
- postgres:10.6

stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_DB: grostore
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: "password"

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - grostore-rest/build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check --stacktrace
  only:
    - master
    - develop

deploy:
  stage: deploy
  script:
    - ./gradlew ftp
  only:
    - master
    - develop

after_script:
- echo "End CI"