export default {
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  CLEAR_PRODUCT_LIST: 'CLEAR_PRODUCT_LIST',
  SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
  SET_LOADING: 'SET_LOADING',
  SET_PRODUCT_FIELDS: 'SET_PRODUCT_FIELDS',
}
