export default {
  ADD_PRICE_LIST: 'ADD_PRICE_LIST',
  ADD_PRICE_LISTS: 'ADD_PRICE_LISTS',
  REMOVE_PRICE_LIST: 'REMOVE_PRICE_LIST',
  CLEAR_PRICE_LISTS: 'CLEAR_PRICE_LISTS',
  SET_PRODUCT_IMPORT: 'SET_PRODUCT_IMPORT',
  SET_PRODUCT_IMPORT_FIELDS: 'SET_PRODUCT_IMPORT_FIELDS',
  SET_LOADING: 'SET_LOADING'
}
