export const SET_CATEGORIES_TREE = 'SET_CATEGORIES_TREE'
export const SET_CATEGORY = 'SET_CATEGORY'

export const SET_PRODUCTS_LIST = 'SET_PRODUCTS_LIST'
export const SET_PRODUCTS_DETAIL = 'SET_PRODUCTS_DETAIL'
