export default {
  ADD_TASK: 'ADD_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  REMOVE_TASKS: 'REMOVE_TASKS',
  UPDATE_TASK: 'UPDATE_TASK',
  CLEAR_TASK_LIST: 'CLEAR_TASK_LIST',
  SET_TASK_LIST: 'SET_TASK_LIST',
  SET_PAGINATION: 'SET_PAGINATION',
  SET_LOADING: 'SET_LOADING'
}
